tasks:
  - name: 1. Base de Datos (MySQL)
    command: |
      docker start rifas-db || docker run --name rifas-db -p 3306:3306 -e MYSQL_ROOT_PASSWORD=rootpassword -e MYSQL_DATABASE=rifas_db -e MYSQL_USER=rifas_user -e MYSQL_PASSWORD=password -d mysql:8.0

  - name: 2. Backend (Laravel)
    init: |
      cd api
      composer install
      cp .env.example .env || true
      php artisan key:generate
    command: |
      cd api
      echo "Esperando 20 segundos a que la base de datos se inicie..."
      sleep 20
      php artisan migrate:fresh --seed
      php artisan serve --host=0.0.0.0 --port=8000

  - name: 3. Frontend (Next.js)
    init: |
      cd web
      npm install
    command: |
      cd web
      npm run dev

ports:
  - port: 3000
    onOpen: open-preview
  - port: 8000
    onOpen: open-browser
  - port: 3306
    onOpen: ignore