tasks:
  - name: Instalador de Laravel
    init: |
      cd api
      composer install
      cp .env.example .env
      php artisan key:generate
    command: |
      cd api
      php artisan migrate
      php artisan serve --host=0.0.0.0 --port=8000

ports:
  - port: 3000
    onOpen: open-preview
  - port: 8000
    onOpen: ignore
  - port: 3306
    onOpen: ignore

# Configuración de la base de datos MySQL
mysql:
  image: mysql:8.0
  database: rifas_db
  user: rifas_user
  password: password
  rootPassword: rootpassword